# Default values for abpm-drools.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name:
  metadata: my-drools
  service: my-drools-svc
  app: drools

replicaCount: 1

image:
  repository: abpm-drools
  tag: 1.0.0-SNAPSHOT
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

ingress:
  enabled: false